const linkStyles = [
  "text-lg",
  "cursor-pointer",
  "active:opacity-45",
  "font-bold",
  "border-2",
  "border-solid",
  "border-darkGray",
  "border-opacity-20",
  "flex",
  "items-center",
  "px-2",
  "rounded-2xl",
  "after:bg-white",
  "after:absolute",
  "after:h-[2px]",
  "after:w-0",
  "after:bottom-0",
  "after:left-0",
  "hover:after:w-[90%]",
  "after:transition-all",
  "after:duration-300",
  "relative",
  "md:text-2xl",
  "w-max",
];

export default linkStyles;
