export const linkStyles = [
  "text-lg",
  "text-accent",
  "cursor-pointer",
  "active:opacity-45",
  "font-bold",
  "after:bg-accent",
  "after:absolute",
  "after:h-[2px]",
  "after:w-0",
  "after:bottom-0",
  "after:left-0",
  "hover:after:w-[90%]",
  "after:transition-all",
  "after:duration-300",
  "relative",
];
